# Generated by Django 6.0 on 2025-12-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_name_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['name'], 'verbose_name': 'Корзина'},
        ),
    ]
